// Copyright (c) 2023 Snowflake Inc. All rights reserved.
//
//Licensed under the Apache License, Version 2.0 (the
//"License"); you may not use this file except in compliance
//with the License.  You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing,
//software distributed under the License is distributed on an
//"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
//KIND, either express or implied.  See the License for the
//specific language governing permissions and limitations
//under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.4
// source: network.proto

package network

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enum for TCP check failure reasons
type TCPCheckFailureReason int32

const (
	TCPCheckFailureReason_UNKNOWN            TCPCheckFailureReason = 0
	TCPCheckFailureReason_TIMEOUT            TCPCheckFailureReason = 1
	TCPCheckFailureReason_CONNECTION_REFUSED TCPCheckFailureReason = 2
	TCPCheckFailureReason_NO_SUCH_HOST       TCPCheckFailureReason = 3
)

// Enum value maps for TCPCheckFailureReason.
var (
	TCPCheckFailureReason_name = map[int32]string{
		0: "UNKNOWN",
		1: "TIMEOUT",
		2: "CONNECTION_REFUSED",
		3: "NO_SUCH_HOST",
	}
	TCPCheckFailureReason_value = map[string]int32{
		"UNKNOWN":            0,
		"TIMEOUT":            1,
		"CONNECTION_REFUSED": 2,
		"NO_SUCH_HOST":       3,
	}
)

func (x TCPCheckFailureReason) Enum() *TCPCheckFailureReason {
	p := new(TCPCheckFailureReason)
	*p = x
	return p
}

func (x TCPCheckFailureReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TCPCheckFailureReason) Descriptor() protoreflect.EnumDescriptor {
	return file_network_proto_enumTypes[0].Descriptor()
}

func (TCPCheckFailureReason) Type() protoreflect.EnumType {
	return &file_network_proto_enumTypes[0]
}

func (x TCPCheckFailureReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TCPCheckFailureReason.Descriptor instead.
func (TCPCheckFailureReason) EnumDescriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{0}
}

// TCP Check describes the request to make check of tcp connectivity check
type TCPCheckRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The hostname to check
	Hostname string `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	// The port to check
	Port uint32 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	// The timeout duration
	Timeout       *durationpb.Duration `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TCPCheckRequest) Reset() {
	*x = TCPCheckRequest{}
	mi := &file_network_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TCPCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TCPCheckRequest) ProtoMessage() {}

func (x *TCPCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TCPCheckRequest.ProtoReflect.Descriptor instead.
func (*TCPCheckRequest) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{0}
}

func (x *TCPCheckRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *TCPCheckRequest) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *TCPCheckRequest) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

// TCPCheckReply describes the result of a rpc
type TCPCheckReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	FailReason    *TCPCheckFailureReason `protobuf:"varint,2,opt,name=fail_reason,json=failReason,proto3,enum=Network.TCPCheckFailureReason,oneof" json:"fail_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TCPCheckReply) Reset() {
	*x = TCPCheckReply{}
	mi := &file_network_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TCPCheckReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TCPCheckReply) ProtoMessage() {}

func (x *TCPCheckReply) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TCPCheckReply.ProtoReflect.Descriptor instead.
func (*TCPCheckReply) Descriptor() ([]byte, []int) {
	return file_network_proto_rawDescGZIP(), []int{1}
}

func (x *TCPCheckReply) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *TCPCheckReply) GetFailReason() TCPCheckFailureReason {
	if x != nil && x.FailReason != nil {
		return *x.FailReason
	}
	return TCPCheckFailureReason_UNKNOWN
}

var File_network_proto protoreflect.FileDescriptor

const file_network_proto_rawDesc = "" +
	"\n" +
	"\rnetwork.proto\x12\aNetwork\x1a\x1egoogle/protobuf/duration.proto\"v\n" +
	"\x0fTCPCheckRequest\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\x123\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\atimeout\"u\n" +
	"\rTCPCheckReply\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12D\n" +
	"\vfail_reason\x18\x02 \x01(\x0e2\x1e.Network.TCPCheckFailureReasonH\x00R\n" +
	"failReason\x88\x01\x01B\x0e\n" +
	"\f_fail_reason*[\n" +
	"\x15TCPCheckFailureReason\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aTIMEOUT\x10\x01\x12\x16\n" +
	"\x12CONNECTION_REFUSED\x10\x02\x12\x10\n" +
	"\fNO_SUCH_HOST\x10\x032I\n" +
	"\aNetwork\x12>\n" +
	"\bTCPCheck\x12\x18.Network.TCPCheckRequest\x1a\x16.Network.TCPCheckReply\"\x00B-Z+github.com/Snowflake-Labs/sansshell/networkb\x06proto3"

var (
	file_network_proto_rawDescOnce sync.Once
	file_network_proto_rawDescData []byte
)

func file_network_proto_rawDescGZIP() []byte {
	file_network_proto_rawDescOnce.Do(func() {
		file_network_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_network_proto_rawDesc), len(file_network_proto_rawDesc)))
	})
	return file_network_proto_rawDescData
}

var file_network_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_network_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_network_proto_goTypes = []any{
	(TCPCheckFailureReason)(0),  // 0: Network.TCPCheckFailureReason
	(*TCPCheckRequest)(nil),     // 1: Network.TCPCheckRequest
	(*TCPCheckReply)(nil),       // 2: Network.TCPCheckReply
	(*durationpb.Duration)(nil), // 3: google.protobuf.Duration
}
var file_network_proto_depIdxs = []int32{
	3, // 0: Network.TCPCheckRequest.timeout:type_name -> google.protobuf.Duration
	0, // 1: Network.TCPCheckReply.fail_reason:type_name -> Network.TCPCheckFailureReason
	1, // 2: Network.Network.TCPCheck:input_type -> Network.TCPCheckRequest
	2, // 3: Network.Network.TCPCheck:output_type -> Network.TCPCheckReply
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_network_proto_init() }
func file_network_proto_init() {
	if File_network_proto != nil {
		return
	}
	file_network_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_network_proto_rawDesc), len(file_network_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_network_proto_goTypes,
		DependencyIndexes: file_network_proto_depIdxs,
		EnumInfos:         file_network_proto_enumTypes,
		MessageInfos:      file_network_proto_msgTypes,
	}.Build()
	File_network_proto = out.File
	file_network_proto_goTypes = nil
	file_network_proto_depIdxs = nil
}
