// Copyright (c) 2019 Snowflake Inc. All rights reserved.
//
//Licensed under the Apache License, Version 2.0 (the
//"License"); you may not use this file except in compliance
//with the License.  You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing,
//software distributed under the License is distributed on an
//"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
//KIND, either express or implied.  See the License for the
//specific language governing permissions and limitations
//under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.4
// source: service.proto

package service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A SystemType specifies the service management system
// on which to operate.
// The 'unknown' value, if specified in a request, will
// map to an appropriate implementation-defined default
// for the system running SansShell.
type SystemType int32

const (
	SystemType_SYSTEM_TYPE_UNKNOWN SystemType = 0
	SystemType_SYSTEM_TYPE_SYSTEMD SystemType = 1
)

// Enum value maps for SystemType.
var (
	SystemType_name = map[int32]string{
		0: "SYSTEM_TYPE_UNKNOWN",
		1: "SYSTEM_TYPE_SYSTEMD",
	}
	SystemType_value = map[string]int32{
		"SYSTEM_TYPE_UNKNOWN": 0,
		"SYSTEM_TYPE_SYSTEMD": 1,
	}
)

func (x SystemType) Enum() *SystemType {
	p := new(SystemType)
	*p = x
	return p
}

func (x SystemType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SystemType) Descriptor() protoreflect.EnumDescriptor {
	return file_service_proto_enumTypes[0].Descriptor()
}

func (SystemType) Type() protoreflect.EnumType {
	return &file_service_proto_enumTypes[0]
}

func (x SystemType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SystemType.Descriptor instead.
func (SystemType) EnumDescriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

// The operational status of the service.
type Status int32

const (
	Status_STATUS_UNKNOWN Status = 0
	Status_STATUS_RUNNING Status = 1
	Status_STATUS_STOPPED Status = 2
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNKNOWN",
		1: "STATUS_RUNNING",
		2: "STATUS_STOPPED",
	}
	Status_value = map[string]int32{
		"STATUS_UNKNOWN": 0,
		"STATUS_RUNNING": 1,
		"STATUS_STOPPED": 2,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_service_proto_enumTypes[1].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_service_proto_enumTypes[1]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{1}
}

// An action taken to modify the operational status of a
// service.
type Action int32

const (
	Action_ACTION_UNKNOWN Action = 0
	Action_ACTION_START   Action = 1
	Action_ACTION_STOP    Action = 2
	Action_ACTION_RESTART Action = 3
	Action_ACTION_ENABLE  Action = 4
	Action_ACTION_DISABLE Action = 5
	Action_ACTION_RELOAD  Action = 6
)

// Enum value maps for Action.
var (
	Action_name = map[int32]string{
		0: "ACTION_UNKNOWN",
		1: "ACTION_START",
		2: "ACTION_STOP",
		3: "ACTION_RESTART",
		4: "ACTION_ENABLE",
		5: "ACTION_DISABLE",
		6: "ACTION_RELOAD",
	}
	Action_value = map[string]int32{
		"ACTION_UNKNOWN": 0,
		"ACTION_START":   1,
		"ACTION_STOP":    2,
		"ACTION_RESTART": 3,
		"ACTION_ENABLE":  4,
		"ACTION_DISABLE": 5,
		"ACTION_RELOAD":  6,
	}
)

func (x Action) Enum() *Action {
	p := new(Action)
	*p = x
	return p
}

func (x Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Action) Descriptor() protoreflect.EnumDescriptor {
	return file_service_proto_enumTypes[2].Descriptor()
}

func (Action) Type() protoreflect.EnumType {
	return &file_service_proto_enumTypes[2]
}

func (x Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Action.Descriptor instead.
func (Action) EnumDescriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{2}
}

// ServiceStatus pairs a service with it's current status.
type ServiceStatus struct {
	state                             protoimpl.MessageState `protogen:"open.v1"`
	ServiceName                       string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Status                            Status                 `protobuf:"varint,2,opt,name=status,proto3,enum=Service.Status" json:"status,omitempty"`
	RecentTimestampReachCurrentStatus *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=recent_timestamp_reach_current_status,json=recentTimestampReachCurrentStatus,proto3" json:"recent_timestamp_reach_current_status,omitempty"`
	unknownFields                     protoimpl.UnknownFields
	sizeCache                         protoimpl.SizeCache
}

func (x *ServiceStatus) Reset() {
	*x = ServiceStatus{}
	mi := &file_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceStatus) ProtoMessage() {}

func (x *ServiceStatus) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceStatus.ProtoReflect.Descriptor instead.
func (*ServiceStatus) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

func (x *ServiceStatus) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *ServiceStatus) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNKNOWN
}

func (x *ServiceStatus) GetRecentTimestampReachCurrentStatus() *timestamppb.Timestamp {
	if x != nil {
		return x.RecentTimestampReachCurrentStatus
	}
	return nil
}

// A request to list all configured services for a single
// system type.
type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SystemType    SystemType             `protobuf:"varint,1,opt,name=system_type,json=systemType,proto3,enum=Service.SystemType" json:"system_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{1}
}

func (x *ListRequest) GetSystemType() SystemType {
	if x != nil {
		return x.SystemType
	}
	return SystemType_SYSTEM_TYPE_UNKNOWN
}

// A list of all configured services, with their attendent
// status.
type ListReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SystemType    SystemType             `protobuf:"varint,1,opt,name=system_type,json=systemType,proto3,enum=Service.SystemType" json:"system_type,omitempty"`
	Services      []*ServiceStatus       `protobuf:"bytes,2,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReply) Reset() {
	*x = ListReply{}
	mi := &file_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReply) ProtoMessage() {}

func (x *ListReply) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReply.ProtoReflect.Descriptor instead.
func (*ListReply) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{2}
}

func (x *ListReply) GetSystemType() SystemType {
	if x != nil {
		return x.SystemType
	}
	return SystemType_SYSTEM_TYPE_UNKNOWN
}

func (x *ListReply) GetServices() []*ServiceStatus {
	if x != nil {
		return x.Services
	}
	return nil
}

// A request to list the status of a single service.
type StatusRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SystemType       SystemType             `protobuf:"varint,1,opt,name=system_type,json=systemType,proto3,enum=Service.SystemType" json:"system_type,omitempty"`
	ServiceName      string                 `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	DisplayTimestamp bool                   `protobuf:"varint,3,opt,name=display_timestamp,json=displayTimestamp,proto3" json:"display_timestamp,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{3}
}

func (x *StatusRequest) GetSystemType() SystemType {
	if x != nil {
		return x.SystemType
	}
	return SystemType_SYSTEM_TYPE_UNKNOWN
}

func (x *StatusRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *StatusRequest) GetDisplayTimestamp() bool {
	if x != nil {
		return x.DisplayTimestamp
	}
	return false
}

// A StatusReply contains the operational status of
// a single service.
type StatusReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SystemType    SystemType             `protobuf:"varint,1,opt,name=system_type,json=systemType,proto3,enum=Service.SystemType" json:"system_type,omitempty"`
	ServiceStatus *ServiceStatus         `protobuf:"bytes,2,opt,name=service_status,json=serviceStatus,proto3" json:"service_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusReply) Reset() {
	*x = StatusReply{}
	mi := &file_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusReply) ProtoMessage() {}

func (x *StatusReply) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusReply.ProtoReflect.Descriptor instead.
func (*StatusReply) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{4}
}

func (x *StatusReply) GetSystemType() SystemType {
	if x != nil {
		return x.SystemType
	}
	return SystemType_SYSTEM_TYPE_UNKNOWN
}

func (x *StatusReply) GetServiceStatus() *ServiceStatus {
	if x != nil {
		return x.ServiceStatus
	}
	return nil
}

// A request to alter the state of a single service.
type ActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SystemType    SystemType             `protobuf:"varint,1,opt,name=system_type,json=systemType,proto3,enum=Service.SystemType" json:"system_type,omitempty"`
	ServiceName   string                 `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Action        Action                 `protobuf:"varint,3,opt,name=action,proto3,enum=Service.Action" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionRequest) Reset() {
	*x = ActionRequest{}
	mi := &file_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionRequest) ProtoMessage() {}

func (x *ActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionRequest.ProtoReflect.Descriptor instead.
func (*ActionRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{5}
}

func (x *ActionRequest) GetSystemType() SystemType {
	if x != nil {
		return x.SystemType
	}
	return SystemType_SYSTEM_TYPE_UNKNOWN
}

func (x *ActionRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *ActionRequest) GetAction() Action {
	if x != nil {
		return x.Action
	}
	return Action_ACTION_UNKNOWN
}

// The result of a request to alter the status of a service.
type ActionReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SystemType    SystemType             `protobuf:"varint,1,opt,name=system_type,json=systemType,proto3,enum=Service.SystemType" json:"system_type,omitempty"`
	ServiceName   string                 `protobuf:"bytes,2,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionReply) Reset() {
	*x = ActionReply{}
	mi := &file_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionReply) ProtoMessage() {}

func (x *ActionReply) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionReply.ProtoReflect.Descriptor instead.
func (*ActionReply) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{6}
}

func (x *ActionReply) GetSystemType() SystemType {
	if x != nil {
		return x.SystemType
	}
	return SystemType_SYSTEM_TYPE_UNKNOWN
}

func (x *ActionReply) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

var File_service_proto protoreflect.FileDescriptor

const file_service_proto_rawDesc = "" +
	"\n" +
	"\rservice.proto\x12\aService\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc9\x01\n" +
	"\rServiceStatus\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12'\n" +
	"\x06status\x18\x02 \x01(\x0e2\x0f.Service.StatusR\x06status\x12l\n" +
	"%recent_timestamp_reach_current_status\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR!recentTimestampReachCurrentStatus\"C\n" +
	"\vListRequest\x124\n" +
	"\vsystem_type\x18\x01 \x01(\x0e2\x13.Service.SystemTypeR\n" +
	"systemType\"u\n" +
	"\tListReply\x124\n" +
	"\vsystem_type\x18\x01 \x01(\x0e2\x13.Service.SystemTypeR\n" +
	"systemType\x122\n" +
	"\bservices\x18\x02 \x03(\v2\x16.Service.ServiceStatusR\bservices\"\x95\x01\n" +
	"\rStatusRequest\x124\n" +
	"\vsystem_type\x18\x01 \x01(\x0e2\x13.Service.SystemTypeR\n" +
	"systemType\x12!\n" +
	"\fservice_name\x18\x02 \x01(\tR\vserviceName\x12+\n" +
	"\x11display_timestamp\x18\x03 \x01(\bR\x10displayTimestamp\"\x82\x01\n" +
	"\vStatusReply\x124\n" +
	"\vsystem_type\x18\x01 \x01(\x0e2\x13.Service.SystemTypeR\n" +
	"systemType\x12=\n" +
	"\x0eservice_status\x18\x02 \x01(\v2\x16.Service.ServiceStatusR\rserviceStatus\"\x91\x01\n" +
	"\rActionRequest\x124\n" +
	"\vsystem_type\x18\x01 \x01(\x0e2\x13.Service.SystemTypeR\n" +
	"systemType\x12!\n" +
	"\fservice_name\x18\x02 \x01(\tR\vserviceName\x12'\n" +
	"\x06action\x18\x03 \x01(\x0e2\x0f.Service.ActionR\x06action\"f\n" +
	"\vActionReply\x124\n" +
	"\vsystem_type\x18\x01 \x01(\x0e2\x13.Service.SystemTypeR\n" +
	"systemType\x12!\n" +
	"\fservice_name\x18\x02 \x01(\tR\vserviceName*>\n" +
	"\n" +
	"SystemType\x12\x17\n" +
	"\x13SYSTEM_TYPE_UNKNOWN\x10\x00\x12\x17\n" +
	"\x13SYSTEM_TYPE_SYSTEMD\x10\x01*D\n" +
	"\x06Status\x12\x12\n" +
	"\x0eSTATUS_UNKNOWN\x10\x00\x12\x12\n" +
	"\x0eSTATUS_RUNNING\x10\x01\x12\x12\n" +
	"\x0eSTATUS_STOPPED\x10\x02*\x8d\x01\n" +
	"\x06Action\x12\x12\n" +
	"\x0eACTION_UNKNOWN\x10\x00\x12\x10\n" +
	"\fACTION_START\x10\x01\x12\x0f\n" +
	"\vACTION_STOP\x10\x02\x12\x12\n" +
	"\x0eACTION_RESTART\x10\x03\x12\x11\n" +
	"\rACTION_ENABLE\x10\x04\x12\x12\n" +
	"\x0eACTION_DISABLE\x10\x05\x12\x11\n" +
	"\rACTION_RELOAD\x10\x062\xb1\x01\n" +
	"\aService\x122\n" +
	"\x04List\x12\x14.Service.ListRequest\x1a\x12.Service.ListReply\"\x00\x128\n" +
	"\x06Status\x12\x16.Service.StatusRequest\x1a\x14.Service.StatusReply\"\x00\x128\n" +
	"\x06Action\x12\x16.Service.ActionRequest\x1a\x14.Service.ActionReply\"\x00B6Z4github.com/Snowflake-Labs/sansshell/services/serviceb\x06proto3"

var (
	file_service_proto_rawDescOnce sync.Once
	file_service_proto_rawDescData []byte
)

func file_service_proto_rawDescGZIP() []byte {
	file_service_proto_rawDescOnce.Do(func() {
		file_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)))
	})
	return file_service_proto_rawDescData
}

var file_service_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_service_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_service_proto_goTypes = []any{
	(SystemType)(0),               // 0: Service.SystemType
	(Status)(0),                   // 1: Service.Status
	(Action)(0),                   // 2: Service.Action
	(*ServiceStatus)(nil),         // 3: Service.ServiceStatus
	(*ListRequest)(nil),           // 4: Service.ListRequest
	(*ListReply)(nil),             // 5: Service.ListReply
	(*StatusRequest)(nil),         // 6: Service.StatusRequest
	(*StatusReply)(nil),           // 7: Service.StatusReply
	(*ActionRequest)(nil),         // 8: Service.ActionRequest
	(*ActionReply)(nil),           // 9: Service.ActionReply
	(*timestamppb.Timestamp)(nil), // 10: google.protobuf.Timestamp
}
var file_service_proto_depIdxs = []int32{
	1,  // 0: Service.ServiceStatus.status:type_name -> Service.Status
	10, // 1: Service.ServiceStatus.recent_timestamp_reach_current_status:type_name -> google.protobuf.Timestamp
	0,  // 2: Service.ListRequest.system_type:type_name -> Service.SystemType
	0,  // 3: Service.ListReply.system_type:type_name -> Service.SystemType
	3,  // 4: Service.ListReply.services:type_name -> Service.ServiceStatus
	0,  // 5: Service.StatusRequest.system_type:type_name -> Service.SystemType
	0,  // 6: Service.StatusReply.system_type:type_name -> Service.SystemType
	3,  // 7: Service.StatusReply.service_status:type_name -> Service.ServiceStatus
	0,  // 8: Service.ActionRequest.system_type:type_name -> Service.SystemType
	2,  // 9: Service.ActionRequest.action:type_name -> Service.Action
	0,  // 10: Service.ActionReply.system_type:type_name -> Service.SystemType
	4,  // 11: Service.Service.List:input_type -> Service.ListRequest
	6,  // 12: Service.Service.Status:input_type -> Service.StatusRequest
	8,  // 13: Service.Service.Action:input_type -> Service.ActionRequest
	5,  // 14: Service.Service.List:output_type -> Service.ListReply
	7,  // 15: Service.Service.Status:output_type -> Service.StatusReply
	9,  // 16: Service.Service.Action:output_type -> Service.ActionReply
	14, // [14:17] is the sub-list for method output_type
	11, // [11:14] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
		EnumInfos:         file_service_proto_enumTypes,
		MessageInfos:      file_service_proto_msgTypes,
	}.Build()
	File_service_proto = out.File
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
