// Copyright (c) 2023 Snowflake Inc. All rights reserved.
//
//Licensed under the Apache License, Version 2.0 (the
//"License"); you may not use this file except in compliance
//with the License.  You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing,
//software distributed under the License is distributed on an
//"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
//KIND, either express or implied.  See the License for the
//specific language governing permissions and limitations
//under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: sysinfo.proto

package sysinfo

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SysInfo_Uptime_FullMethodName  = "/SysInfo.SysInfo/Uptime"
	SysInfo_Dmesg_FullMethodName   = "/SysInfo.SysInfo/Dmesg"
	SysInfo_Journal_FullMethodName = "/SysInfo.SysInfo/Journal"
)

// SysInfoClient is the client API for SysInfo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The SysInfo service definition.
type SysInfoClient interface {
	// Uptime return
	Uptime(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*UptimeReply, error)
	// display kernel-related messages
	Dmesg(ctx context.Context, in *DmesgRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DmesgReply], error)
	// Journal returns journal entries collected by systemd journald service
	Journal(ctx context.Context, in *JournalRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[JournalReply], error)
}

type sysInfoClient struct {
	cc grpc.ClientConnInterface
}

func NewSysInfoClient(cc grpc.ClientConnInterface) SysInfoClient {
	return &sysInfoClient{cc}
}

func (c *sysInfoClient) Uptime(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*UptimeReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UptimeReply)
	err := c.cc.Invoke(ctx, SysInfo_Uptime_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysInfoClient) Dmesg(ctx context.Context, in *DmesgRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DmesgReply], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SysInfo_ServiceDesc.Streams[0], SysInfo_Dmesg_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DmesgRequest, DmesgReply]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SysInfo_DmesgClient = grpc.ServerStreamingClient[DmesgReply]

func (c *sysInfoClient) Journal(ctx context.Context, in *JournalRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[JournalReply], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SysInfo_ServiceDesc.Streams[1], SysInfo_Journal_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[JournalRequest, JournalReply]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SysInfo_JournalClient = grpc.ServerStreamingClient[JournalReply]

// SysInfoServer is the server API for SysInfo service.
// All implementations should embed UnimplementedSysInfoServer
// for forward compatibility.
//
// The SysInfo service definition.
type SysInfoServer interface {
	// Uptime return
	Uptime(context.Context, *emptypb.Empty) (*UptimeReply, error)
	// display kernel-related messages
	Dmesg(*DmesgRequest, grpc.ServerStreamingServer[DmesgReply]) error
	// Journal returns journal entries collected by systemd journald service
	Journal(*JournalRequest, grpc.ServerStreamingServer[JournalReply]) error
}

// UnimplementedSysInfoServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSysInfoServer struct{}

func (UnimplementedSysInfoServer) Uptime(context.Context, *emptypb.Empty) (*UptimeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Uptime not implemented")
}
func (UnimplementedSysInfoServer) Dmesg(*DmesgRequest, grpc.ServerStreamingServer[DmesgReply]) error {
	return status.Errorf(codes.Unimplemented, "method Dmesg not implemented")
}
func (UnimplementedSysInfoServer) Journal(*JournalRequest, grpc.ServerStreamingServer[JournalReply]) error {
	return status.Errorf(codes.Unimplemented, "method Journal not implemented")
}
func (UnimplementedSysInfoServer) testEmbeddedByValue() {}

// UnsafeSysInfoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SysInfoServer will
// result in compilation errors.
type UnsafeSysInfoServer interface {
	mustEmbedUnimplementedSysInfoServer()
}

func RegisterSysInfoServer(s grpc.ServiceRegistrar, srv SysInfoServer) {
	// If the following call pancis, it indicates UnimplementedSysInfoServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SysInfo_ServiceDesc, srv)
}

func _SysInfo_Uptime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysInfoServer).Uptime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysInfo_Uptime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysInfoServer).Uptime(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysInfo_Dmesg_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DmesgRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SysInfoServer).Dmesg(m, &grpc.GenericServerStream[DmesgRequest, DmesgReply]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SysInfo_DmesgServer = grpc.ServerStreamingServer[DmesgReply]

func _SysInfo_Journal_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(JournalRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SysInfoServer).Journal(m, &grpc.GenericServerStream[JournalRequest, JournalReply]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SysInfo_JournalServer = grpc.ServerStreamingServer[JournalReply]

// SysInfo_ServiceDesc is the grpc.ServiceDesc for SysInfo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SysInfo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "SysInfo.SysInfo",
	HandlerType: (*SysInfoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Uptime",
			Handler:    _SysInfo_Uptime_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Dmesg",
			Handler:       _SysInfo_Dmesg_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Journal",
			Handler:       _SysInfo_Journal_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "sysinfo.proto",
}
