// Copyright (c) 2019 Snowflake Inc. All rights reserved.
//
//Licensed under the Apache License, Version 2.0 (the
//"License"); you may not use this file except in compliance
//with the License.  You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing,
//software distributed under the License is distributed on an
//"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
//KIND, either express or implied.  See the License for the
//specific language governing permissions and limitations
//under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.29.3
// source: services/fdbexec/fdbexec.proto

package fdbexec

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FdbExecRequest describes what to execute
type FdbExecRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Command string   `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Args    []string `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	// User to execute command as, equivalent of `sudo -u <user> <command>`.
	User string `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *FdbExecRequest) Reset() {
	*x = FdbExecRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_fdbexec_fdbexec_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FdbExecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FdbExecRequest) ProtoMessage() {}

func (x *FdbExecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_fdbexec_fdbexec_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FdbExecRequest.ProtoReflect.Descriptor instead.
func (*FdbExecRequest) Descriptor() ([]byte, []int) {
	return file_services_fdbexec_fdbexec_proto_rawDescGZIP(), []int{0}
}

func (x *FdbExecRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *FdbExecRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *FdbExecRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

// FdbExecResponse describes output of execution
type FdbExecResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stdout  []byte `protobuf:"bytes,1,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr  []byte `protobuf:"bytes,2,opt,name=stderr,proto3" json:"stderr,omitempty"`
	RetCode int32  `protobuf:"varint,3,opt,name=retCode,proto3" json:"retCode,omitempty"`
}

func (x *FdbExecResponse) Reset() {
	*x = FdbExecResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_fdbexec_fdbexec_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FdbExecResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FdbExecResponse) ProtoMessage() {}

func (x *FdbExecResponse) ProtoReflect() protoreflect.Message {
	mi := &file_services_fdbexec_fdbexec_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FdbExecResponse.ProtoReflect.Descriptor instead.
func (*FdbExecResponse) Descriptor() ([]byte, []int) {
	return file_services_fdbexec_fdbexec_proto_rawDescGZIP(), []int{1}
}

func (x *FdbExecResponse) GetStdout() []byte {
	if x != nil {
		return x.Stdout
	}
	return nil
}

func (x *FdbExecResponse) GetStderr() []byte {
	if x != nil {
		return x.Stderr
	}
	return nil
}

func (x *FdbExecResponse) GetRetCode() int32 {
	if x != nil {
		return x.RetCode
	}
	return 0
}

var File_services_fdbexec_fdbexec_proto protoreflect.FileDescriptor

var file_services_fdbexec_fdbexec_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x66, 0x64, 0x62, 0x65, 0x78,
	0x65, 0x63, 0x2f, 0x66, 0x64, 0x62, 0x65, 0x78, 0x65, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x07, 0x46, 0x64, 0x62, 0x45, 0x78, 0x65, 0x63, 0x22, 0x52, 0x0a, 0x0e, 0x46, 0x64, 0x62,
	0x45, 0x78, 0x65, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x63,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x72, 0x67, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x04, 0x61, 0x72, 0x67, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65,
	0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x22, 0x5b, 0x0a,
	0x0f, 0x46, 0x64, 0x62, 0x45, 0x78, 0x65, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x64, 0x6f, 0x75, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x06, 0x73, 0x74, 0x64, 0x6f, 0x75, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x64, 0x65,
	0x72, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x73, 0x74, 0x64, 0x65, 0x72, 0x72,
	0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x07, 0x72, 0x65, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x32, 0x8c, 0x01, 0x0a, 0x07, 0x46,
	0x64, 0x62, 0x45, 0x78, 0x65, 0x63, 0x12, 0x3a, 0x0a, 0x03, 0x52, 0x75, 0x6e, 0x12, 0x17, 0x2e,
	0x46, 0x64, 0x62, 0x45, 0x78, 0x65, 0x63, 0x2e, 0x46, 0x64, 0x62, 0x45, 0x78, 0x65, 0x63, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x46, 0x64, 0x62, 0x45, 0x78, 0x65, 0x63,
	0x2e, 0x46, 0x64, 0x62, 0x45, 0x78, 0x65, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x45, 0x0a, 0x0c, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x52,
	0x75, 0x6e, 0x12, 0x17, 0x2e, 0x46, 0x64, 0x62, 0x45, 0x78, 0x65, 0x63, 0x2e, 0x46, 0x64, 0x62,
	0x45, 0x78, 0x65, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x46, 0x64,
	0x62, 0x45, 0x78, 0x65, 0x63, 0x2e, 0x46, 0x64, 0x62, 0x45, 0x78, 0x65, 0x63, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x42, 0x36, 0x5a, 0x34, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x53, 0x6e, 0x6f, 0x77, 0x66, 0x6c, 0x61, 0x6b,
	0x65, 0x2d, 0x4c, 0x61, 0x62, 0x73, 0x2f, 0x73, 0x61, 0x6e, 0x73, 0x73, 0x68, 0x65, 0x6c, 0x6c,
	0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x66, 0x64, 0x62, 0x65, 0x78, 0x65,
	0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_services_fdbexec_fdbexec_proto_rawDescOnce sync.Once
	file_services_fdbexec_fdbexec_proto_rawDescData = file_services_fdbexec_fdbexec_proto_rawDesc
)

func file_services_fdbexec_fdbexec_proto_rawDescGZIP() []byte {
	file_services_fdbexec_fdbexec_proto_rawDescOnce.Do(func() {
		file_services_fdbexec_fdbexec_proto_rawDescData = protoimpl.X.CompressGZIP(file_services_fdbexec_fdbexec_proto_rawDescData)
	})
	return file_services_fdbexec_fdbexec_proto_rawDescData
}

var file_services_fdbexec_fdbexec_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_services_fdbexec_fdbexec_proto_goTypes = []any{
	(*FdbExecRequest)(nil),  // 0: FdbExec.FdbExecRequest
	(*FdbExecResponse)(nil), // 1: FdbExec.FdbExecResponse
}
var file_services_fdbexec_fdbexec_proto_depIdxs = []int32{
	0, // 0: FdbExec.FdbExec.Run:input_type -> FdbExec.FdbExecRequest
	0, // 1: FdbExec.FdbExec.StreamingRun:input_type -> FdbExec.FdbExecRequest
	1, // 2: FdbExec.FdbExec.Run:output_type -> FdbExec.FdbExecResponse
	1, // 3: FdbExec.FdbExec.StreamingRun:output_type -> FdbExec.FdbExecResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_services_fdbexec_fdbexec_proto_init() }
func file_services_fdbexec_fdbexec_proto_init() {
	if File_services_fdbexec_fdbexec_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_services_fdbexec_fdbexec_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*FdbExecRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_fdbexec_fdbexec_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*FdbExecResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_services_fdbexec_fdbexec_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_fdbexec_fdbexec_proto_goTypes,
		DependencyIndexes: file_services_fdbexec_fdbexec_proto_depIdxs,
		MessageInfos:      file_services_fdbexec_fdbexec_proto_msgTypes,
	}.Build()
	File_services_fdbexec_fdbexec_proto = out.File
	file_services_fdbexec_fdbexec_proto_rawDesc = nil
	file_services_fdbexec_fdbexec_proto_goTypes = nil
	file_services_fdbexec_fdbexec_proto_depIdxs = nil
}
