---
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
    - id: check-yaml
    - id: trailing-whitespace
      files: '(\.go)|(\.md)|(\.yaml)|(\.yml)|(\.json)$'
    - id: end-of-file-fixer
      files: '(\.go)|(\.md)|(\.yaml)|(\.yml)|(\.json)$'
- repo: https://github.com/dnephin/pre-commit-golang
  rev: v0.5.0
  hooks:
    - id: go-fmt
    - id: go-build
    - id: go-mod-tidy
- repo: local
  hooks:
    - id: check-license
      name: check-license
      entry: scripts/check-license.sh
      language: script
      pass_filenames: false
- repo: https://github.com/golangci/golangci-lint
  rev: v1.59.1
  hooks:
      - id: golangci-lint
        args: ['--fast']
        stages: [commit]
