---
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
    - id: check-yaml
    - id: trailing-whitespace
      files: '(\.go)|(\.md)|(\.yaml)|(\.yml)|(\.json)$'
    - id: end-of-file-fixer
      files: '(\.go)|(\.md)|(\.yaml)|(\.yml)|(\.json)$'
- repo: https://github.com/dnephin/pre-commit-golang
  rev: v0.5.0
  hooks:
    - id: go-fmt
    - id: go-build
    - id: go-mod-tidy
