repos:
- repo: https://github.com/dnephin/pre-commit-golang
  rev: v0.5.0
  hooks:
    - id: go-fmt
    - id: go-vet
      args: [-v]
    - id: golangci-lint
      args: [-Dstaticcheck]
    - id: go-build
    - id: go-mod-tidy
