// Copyright (c) 2019 Snowflake Inc. All rights reserved.
//
//Licensed under the Apache License, Version 2.0 (the
//"License"); you may not use this file except in compliance
//with the License.  You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing,
//software distributed under the License is distributed on an
//"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
//KIND, either express or implied.  See the License for the
//specific language governing permissions and limitations
//under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.23.2
// source: power.proto

package power

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Power_Reboot_FullMethodName = "/Power.Power/Reboot"
)

// PowerClient is the client API for Power service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PowerClient interface {
	Reboot(ctx context.Context, in *RebootRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type powerClient struct {
	cc grpc.ClientConnInterface
}

func NewPowerClient(cc grpc.ClientConnInterface) PowerClient {
	return &powerClient{cc}
}

func (c *powerClient) Reboot(ctx context.Context, in *RebootRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Power_Reboot_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PowerServer is the server API for Power service.
// All implementations should embed UnimplementedPowerServer
// for forward compatibility
type PowerServer interface {
	Reboot(context.Context, *RebootRequest) (*emptypb.Empty, error)
}

// UnimplementedPowerServer should be embedded to have forward compatible implementations.
type UnimplementedPowerServer struct {
}

func (UnimplementedPowerServer) Reboot(context.Context, *RebootRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Reboot not implemented")
}

// UnsafePowerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PowerServer will
// result in compilation errors.
type UnsafePowerServer interface {
	mustEmbedUnimplementedPowerServer()
}

func RegisterPowerServer(s grpc.ServiceRegistrar, srv PowerServer) {
	s.RegisterService(&Power_ServiceDesc, srv)
}

func _Power_Reboot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RebootRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PowerServer).Reboot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Power_Reboot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PowerServer).Reboot(ctx, req.(*RebootRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Power_ServiceDesc is the grpc.ServiceDesc for Power service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Power_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Power.Power",
	HandlerType: (*PowerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Reboot",
			Handler:    _Power_Reboot_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "power.proto",
}
