// Copyright (c) 2024 Snowflake Inc. All rights reserved.
//
//Licensed under the Apache License, Version 2.0 (the
//"License"); you may not use this file except in compliance
//with the License.  You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing,
//software distributed under the License is distributed on an
//"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
//KIND, either express or implied.  See the License for the
//specific language governing permissions and limitations
//under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.2
// source: tcpoverrpc.proto

package tcpoverrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/descriptorpb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HostTCPRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Hostname can be specified as either an ip address or domain name.
	Hostname string `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	// The destination port.
	Port int32 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	// Maximum amount of time (in seconds) to wait for a TCP connect to complete.
	TimeoutSeconds int32 `protobuf:"varint,3,opt,name=timeoutSeconds,proto3" json:"timeoutSeconds,omitempty"`
}

func (x *HostTCPRequest) Reset() {
	*x = HostTCPRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tcpoverrpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HostTCPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostTCPRequest) ProtoMessage() {}

func (x *HostTCPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tcpoverrpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostTCPRequest.ProtoReflect.Descriptor instead.
func (*HostTCPRequest) Descriptor() ([]byte, []int) {
	return file_tcpoverrpc_proto_rawDescGZIP(), []int{0}
}

func (x *HostTCPRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *HostTCPRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *HostTCPRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

var File_tcpoverrpc_proto protoreflect.FileDescriptor

var file_tcpoverrpc_proto_rawDesc = []byte{
	0x0a, 0x10, 0x74, 0x63, 0x70, 0x6f, 0x76, 0x65, 0x72, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0a, 0x54, 0x43, 0x50, 0x4f, 0x76, 0x65, 0x72, 0x52, 0x50, 0x43, 0x1a, 0x20,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x68, 0x0a,
	0x0e, 0x48, 0x6f, 0x73, 0x74, 0x54, 0x43, 0x50, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1a, 0x0a, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70,
	0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12,
	0x26, 0x0a, 0x0e, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64,
	0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74,
	0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x32, 0x48, 0x0a, 0x0a, 0x54, 0x43, 0x50, 0x4f, 0x76,
	0x65, 0x72, 0x52, 0x50, 0x43, 0x12, 0x3a, 0x0a, 0x02, 0x4f, 0x6b, 0x12, 0x1a, 0x2e, 0x54, 0x43,
	0x50, 0x4f, 0x76, 0x65, 0x72, 0x52, 0x50, 0x43, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x54, 0x43, 0x50,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22,
	0x00, 0x42, 0x30, 0x5a, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x53, 0x6e, 0x6f, 0x77, 0x66, 0x6c, 0x61, 0x6b, 0x65, 0x2d, 0x4c, 0x61, 0x62, 0x73, 0x2f, 0x73,
	0x61, 0x6e, 0x73, 0x73, 0x68, 0x65, 0x6c, 0x6c, 0x2f, 0x74, 0x63, 0x70, 0x6f, 0x76, 0x65, 0x72,
	0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tcpoverrpc_proto_rawDescOnce sync.Once
	file_tcpoverrpc_proto_rawDescData = file_tcpoverrpc_proto_rawDesc
)

func file_tcpoverrpc_proto_rawDescGZIP() []byte {
	file_tcpoverrpc_proto_rawDescOnce.Do(func() {
		file_tcpoverrpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_tcpoverrpc_proto_rawDescData)
	})
	return file_tcpoverrpc_proto_rawDescData
}

var file_tcpoverrpc_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_tcpoverrpc_proto_goTypes = []interface{}{
	(*HostTCPRequest)(nil), // 0: TCPOverRPC.HostTCPRequest
	(*emptypb.Empty)(nil),  // 1: google.protobuf.Empty
}
var file_tcpoverrpc_proto_depIdxs = []int32{
	0, // 0: TCPOverRPC.TCPOverRPC.Ok:input_type -> TCPOverRPC.HostTCPRequest
	1, // 1: TCPOverRPC.TCPOverRPC.Ok:output_type -> google.protobuf.Empty
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tcpoverrpc_proto_init() }
func file_tcpoverrpc_proto_init() {
	if File_tcpoverrpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tcpoverrpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HostTCPRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tcpoverrpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tcpoverrpc_proto_goTypes,
		DependencyIndexes: file_tcpoverrpc_proto_depIdxs,
		MessageInfos:      file_tcpoverrpc_proto_msgTypes,
	}.Build()
	File_tcpoverrpc_proto = out.File
	file_tcpoverrpc_proto_rawDesc = nil
	file_tcpoverrpc_proto_goTypes = nil
	file_tcpoverrpc_proto_depIdxs = nil
}
