// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package localfile

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// LocalFileClient is the client API for LocalFile service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LocalFileClient interface {
	// Read reads a file from the disk and returns it contents.
	Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (LocalFile_ReadClient, error)
	// Stat returns metadata about a single filesytem path.
	Stat(ctx context.Context, opts ...grpc.CallOption) (LocalFile_StatClient, error)
	// Sum calculates a sum over the data in a single file.
	Sum(ctx context.Context, opts ...grpc.CallOption) (LocalFile_SumClient, error)
	// Write writes a file from the incoming RPC to a local file.
	Write(ctx context.Context, opts ...grpc.CallOption) (LocalFile_WriteClient, error)
	// Copy retrieves a file from the given blob URL and writes it to a local
	// file.
	Copy(ctx context.Context, in *CopyRequest, opts ...grpc.CallOption) (*NullReply, error)
}

type localFileClient struct {
	cc grpc.ClientConnInterface
}

func NewLocalFileClient(cc grpc.ClientConnInterface) LocalFileClient {
	return &localFileClient{cc}
}

func (c *localFileClient) Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (LocalFile_ReadClient, error) {
	stream, err := c.cc.NewStream(ctx, &LocalFile_ServiceDesc.Streams[0], "/LocalFile.LocalFile/Read", opts...)
	if err != nil {
		return nil, err
	}
	x := &localFileReadClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type LocalFile_ReadClient interface {
	Recv() (*ReadReply, error)
	grpc.ClientStream
}

type localFileReadClient struct {
	grpc.ClientStream
}

func (x *localFileReadClient) Recv() (*ReadReply, error) {
	m := new(ReadReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *localFileClient) Stat(ctx context.Context, opts ...grpc.CallOption) (LocalFile_StatClient, error) {
	stream, err := c.cc.NewStream(ctx, &LocalFile_ServiceDesc.Streams[1], "/LocalFile.LocalFile/Stat", opts...)
	if err != nil {
		return nil, err
	}
	x := &localFileStatClient{stream}
	return x, nil
}

type LocalFile_StatClient interface {
	Send(*StatRequest) error
	Recv() (*StatReply, error)
	grpc.ClientStream
}

type localFileStatClient struct {
	grpc.ClientStream
}

func (x *localFileStatClient) Send(m *StatRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *localFileStatClient) Recv() (*StatReply, error) {
	m := new(StatReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *localFileClient) Sum(ctx context.Context, opts ...grpc.CallOption) (LocalFile_SumClient, error) {
	stream, err := c.cc.NewStream(ctx, &LocalFile_ServiceDesc.Streams[2], "/LocalFile.LocalFile/Sum", opts...)
	if err != nil {
		return nil, err
	}
	x := &localFileSumClient{stream}
	return x, nil
}

type LocalFile_SumClient interface {
	Send(*SumRequest) error
	Recv() (*SumReply, error)
	grpc.ClientStream
}

type localFileSumClient struct {
	grpc.ClientStream
}

func (x *localFileSumClient) Send(m *SumRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *localFileSumClient) Recv() (*SumReply, error) {
	m := new(SumReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *localFileClient) Write(ctx context.Context, opts ...grpc.CallOption) (LocalFile_WriteClient, error) {
	stream, err := c.cc.NewStream(ctx, &LocalFile_ServiceDesc.Streams[3], "/LocalFile.LocalFile/Write", opts...)
	if err != nil {
		return nil, err
	}
	x := &localFileWriteClient{stream}
	return x, nil
}

type LocalFile_WriteClient interface {
	Send(*WriteRequest) error
	CloseAndRecv() (*NullReply, error)
	grpc.ClientStream
}

type localFileWriteClient struct {
	grpc.ClientStream
}

func (x *localFileWriteClient) Send(m *WriteRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *localFileWriteClient) CloseAndRecv() (*NullReply, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(NullReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *localFileClient) Copy(ctx context.Context, in *CopyRequest, opts ...grpc.CallOption) (*NullReply, error) {
	out := new(NullReply)
	err := c.cc.Invoke(ctx, "/LocalFile.LocalFile/Copy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LocalFileServer is the server API for LocalFile service.
// All implementations should embed UnimplementedLocalFileServer
// for forward compatibility
type LocalFileServer interface {
	// Read reads a file from the disk and returns it contents.
	Read(*ReadRequest, LocalFile_ReadServer) error
	// Stat returns metadata about a single filesytem path.
	Stat(LocalFile_StatServer) error
	// Sum calculates a sum over the data in a single file.
	Sum(LocalFile_SumServer) error
	// Write writes a file from the incoming RPC to a local file.
	Write(LocalFile_WriteServer) error
	// Copy retrieves a file from the given blob URL and writes it to a local
	// file.
	Copy(context.Context, *CopyRequest) (*NullReply, error)
}

// UnimplementedLocalFileServer should be embedded to have forward compatible implementations.
type UnimplementedLocalFileServer struct {
}

func (UnimplementedLocalFileServer) Read(*ReadRequest, LocalFile_ReadServer) error {
	return status.Errorf(codes.Unimplemented, "method Read not implemented")
}
func (UnimplementedLocalFileServer) Stat(LocalFile_StatServer) error {
	return status.Errorf(codes.Unimplemented, "method Stat not implemented")
}
func (UnimplementedLocalFileServer) Sum(LocalFile_SumServer) error {
	return status.Errorf(codes.Unimplemented, "method Sum not implemented")
}
func (UnimplementedLocalFileServer) Write(LocalFile_WriteServer) error {
	return status.Errorf(codes.Unimplemented, "method Write not implemented")
}
func (UnimplementedLocalFileServer) Copy(context.Context, *CopyRequest) (*NullReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Copy not implemented")
}

// UnsafeLocalFileServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LocalFileServer will
// result in compilation errors.
type UnsafeLocalFileServer interface {
	mustEmbedUnimplementedLocalFileServer()
}

func RegisterLocalFileServer(s grpc.ServiceRegistrar, srv LocalFileServer) {
	s.RegisterService(&LocalFile_ServiceDesc, srv)
}

func _LocalFile_Read_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReadRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LocalFileServer).Read(m, &localFileReadServer{stream})
}

type LocalFile_ReadServer interface {
	Send(*ReadReply) error
	grpc.ServerStream
}

type localFileReadServer struct {
	grpc.ServerStream
}

func (x *localFileReadServer) Send(m *ReadReply) error {
	return x.ServerStream.SendMsg(m)
}

func _LocalFile_Stat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(LocalFileServer).Stat(&localFileStatServer{stream})
}

type LocalFile_StatServer interface {
	Send(*StatReply) error
	Recv() (*StatRequest, error)
	grpc.ServerStream
}

type localFileStatServer struct {
	grpc.ServerStream
}

func (x *localFileStatServer) Send(m *StatReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *localFileStatServer) Recv() (*StatRequest, error) {
	m := new(StatRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _LocalFile_Sum_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(LocalFileServer).Sum(&localFileSumServer{stream})
}

type LocalFile_SumServer interface {
	Send(*SumReply) error
	Recv() (*SumRequest, error)
	grpc.ServerStream
}

type localFileSumServer struct {
	grpc.ServerStream
}

func (x *localFileSumServer) Send(m *SumReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *localFileSumServer) Recv() (*SumRequest, error) {
	m := new(SumRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _LocalFile_Write_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(LocalFileServer).Write(&localFileWriteServer{stream})
}

type LocalFile_WriteServer interface {
	SendAndClose(*NullReply) error
	Recv() (*WriteRequest, error)
	grpc.ServerStream
}

type localFileWriteServer struct {
	grpc.ServerStream
}

func (x *localFileWriteServer) SendAndClose(m *NullReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *localFileWriteServer) Recv() (*WriteRequest, error) {
	m := new(WriteRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _LocalFile_Copy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CopyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalFileServer).Copy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/LocalFile.LocalFile/Copy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalFileServer).Copy(ctx, req.(*CopyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LocalFile_ServiceDesc is the grpc.ServiceDesc for LocalFile service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LocalFile_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "LocalFile.LocalFile",
	HandlerType: (*LocalFileServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Copy",
			Handler:    _LocalFile_Copy_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Read",
			Handler:       _LocalFile_Read_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Stat",
			Handler:       _LocalFile_Stat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Sum",
			Handler:       _LocalFile_Sum_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Write",
			Handler:       _LocalFile_Write_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "localfile.proto",
}
