// Copyright (c) 2023 Snowflake Inc. All rights reserved.
//
//Licensed under the Apache License, Version 2.0 (the
//"License"); you may not use this file except in compliance
//with the License.  You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing,
//software distributed under the License is distributed on an
//"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
//KIND, either express or implied.  See the License for the
//specific language governing permissions and limitations
//under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.4
// source: tlsinfo.proto

package tlsinfo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TLSCertificateRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ServerAddress      string                 `protobuf:"bytes,1,opt,name=server_address,json=serverAddress,proto3" json:"server_address,omitempty"` // Server's address, including port (e.g. "example.com:443")
	ServerName         string                 `protobuf:"bytes,2,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	InsecureSkipVerify bool                   `protobuf:"varint,3,opt,name=insecure_skip_verify,json=insecureSkipVerify,proto3" json:"insecure_skip_verify,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TLSCertificateRequest) Reset() {
	*x = TLSCertificateRequest{}
	mi := &file_tlsinfo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TLSCertificateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLSCertificateRequest) ProtoMessage() {}

func (x *TLSCertificateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tlsinfo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLSCertificateRequest.ProtoReflect.Descriptor instead.
func (*TLSCertificateRequest) Descriptor() ([]byte, []int) {
	return file_tlsinfo_proto_rawDescGZIP(), []int{0}
}

func (x *TLSCertificateRequest) GetServerAddress() string {
	if x != nil {
		return x.ServerAddress
	}
	return ""
}

func (x *TLSCertificateRequest) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *TLSCertificateRequest) GetInsecureSkipVerify() bool {
	if x != nil {
		return x.InsecureSkipVerify
	}
	return false
}

type TLSCertificate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Issuer        string                 `protobuf:"bytes,1,opt,name=issuer,proto3" json:"issuer,omitempty"`
	Subject       string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	NotBefore     int64                  `protobuf:"varint,3,opt,name=not_before,json=notBefore,proto3" json:"not_before,omitempty"`
	NotAfter      int64                  `protobuf:"varint,4,opt,name=not_after,json=notAfter,proto3" json:"not_after,omitempty"`
	DnsNames      []string               `protobuf:"bytes,5,rep,name=dns_names,json=dnsNames,proto3" json:"dns_names,omitempty"`
	IpAddresses   []string               `protobuf:"bytes,6,rep,name=ip_addresses,json=ipAddresses,proto3" json:"ip_addresses,omitempty"`
	Raw           []byte                 `protobuf:"bytes,7,opt,name=raw,proto3" json:"raw,omitempty"` // Complete ASN.1 DER content (certificate, signature algorithm and signature)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TLSCertificate) Reset() {
	*x = TLSCertificate{}
	mi := &file_tlsinfo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TLSCertificate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLSCertificate) ProtoMessage() {}

func (x *TLSCertificate) ProtoReflect() protoreflect.Message {
	mi := &file_tlsinfo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLSCertificate.ProtoReflect.Descriptor instead.
func (*TLSCertificate) Descriptor() ([]byte, []int) {
	return file_tlsinfo_proto_rawDescGZIP(), []int{1}
}

func (x *TLSCertificate) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

func (x *TLSCertificate) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *TLSCertificate) GetNotBefore() int64 {
	if x != nil {
		return x.NotBefore
	}
	return 0
}

func (x *TLSCertificate) GetNotAfter() int64 {
	if x != nil {
		return x.NotAfter
	}
	return 0
}

func (x *TLSCertificate) GetDnsNames() []string {
	if x != nil {
		return x.DnsNames
	}
	return nil
}

func (x *TLSCertificate) GetIpAddresses() []string {
	if x != nil {
		return x.IpAddresses
	}
	return nil
}

func (x *TLSCertificate) GetRaw() []byte {
	if x != nil {
		return x.Raw
	}
	return nil
}

type TLSCertificateChain struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Certificates  []*TLSCertificate      `protobuf:"bytes,1,rep,name=certificates,proto3" json:"certificates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TLSCertificateChain) Reset() {
	*x = TLSCertificateChain{}
	mi := &file_tlsinfo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TLSCertificateChain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TLSCertificateChain) ProtoMessage() {}

func (x *TLSCertificateChain) ProtoReflect() protoreflect.Message {
	mi := &file_tlsinfo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TLSCertificateChain.ProtoReflect.Descriptor instead.
func (*TLSCertificateChain) Descriptor() ([]byte, []int) {
	return file_tlsinfo_proto_rawDescGZIP(), []int{2}
}

func (x *TLSCertificateChain) GetCertificates() []*TLSCertificate {
	if x != nil {
		return x.Certificates
	}
	return nil
}

var File_tlsinfo_proto protoreflect.FileDescriptor

const file_tlsinfo_proto_rawDesc = "" +
	"\n" +
	"\rtlsinfo.proto\x12\aTLSInfo\"\x91\x01\n" +
	"\x15TLSCertificateRequest\x12%\n" +
	"\x0eserver_address\x18\x01 \x01(\tR\rserverAddress\x12\x1f\n" +
	"\vserver_name\x18\x02 \x01(\tR\n" +
	"serverName\x120\n" +
	"\x14insecure_skip_verify\x18\x03 \x01(\bR\x12insecureSkipVerify\"\xd0\x01\n" +
	"\x0eTLSCertificate\x12\x16\n" +
	"\x06issuer\x18\x01 \x01(\tR\x06issuer\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x1d\n" +
	"\n" +
	"not_before\x18\x03 \x01(\x03R\tnotBefore\x12\x1b\n" +
	"\tnot_after\x18\x04 \x01(\x03R\bnotAfter\x12\x1b\n" +
	"\tdns_names\x18\x05 \x03(\tR\bdnsNames\x12!\n" +
	"\fip_addresses\x18\x06 \x03(\tR\vipAddresses\x12\x10\n" +
	"\x03raw\x18\a \x01(\fR\x03raw\"R\n" +
	"\x13TLSCertificateChain\x12;\n" +
	"\fcertificates\x18\x01 \x03(\v2\x17.TLSInfo.TLSCertificateR\fcertificates2\\\n" +
	"\aTLSInfo\x12Q\n" +
	"\x11GetTLSCertificate\x12\x1e.TLSInfo.TLSCertificateRequest\x1a\x1c.TLSInfo.TLSCertificateChainB-Z+github.com/Snowflake-Labs/sansshell/tlsinfob\x06proto3"

var (
	file_tlsinfo_proto_rawDescOnce sync.Once
	file_tlsinfo_proto_rawDescData []byte
)

func file_tlsinfo_proto_rawDescGZIP() []byte {
	file_tlsinfo_proto_rawDescOnce.Do(func() {
		file_tlsinfo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tlsinfo_proto_rawDesc), len(file_tlsinfo_proto_rawDesc)))
	})
	return file_tlsinfo_proto_rawDescData
}

var file_tlsinfo_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_tlsinfo_proto_goTypes = []any{
	(*TLSCertificateRequest)(nil), // 0: TLSInfo.TLSCertificateRequest
	(*TLSCertificate)(nil),        // 1: TLSInfo.TLSCertificate
	(*TLSCertificateChain)(nil),   // 2: TLSInfo.TLSCertificateChain
}
var file_tlsinfo_proto_depIdxs = []int32{
	1, // 0: TLSInfo.TLSCertificateChain.certificates:type_name -> TLSInfo.TLSCertificate
	0, // 1: TLSInfo.TLSInfo.GetTLSCertificate:input_type -> TLSInfo.TLSCertificateRequest
	2, // 2: TLSInfo.TLSInfo.GetTLSCertificate:output_type -> TLSInfo.TLSCertificateChain
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_tlsinfo_proto_init() }
func file_tlsinfo_proto_init() {
	if File_tlsinfo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tlsinfo_proto_rawDesc), len(file_tlsinfo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tlsinfo_proto_goTypes,
		DependencyIndexes: file_tlsinfo_proto_depIdxs,
		MessageInfos:      file_tlsinfo_proto_msgTypes,
	}.Build()
	File_tlsinfo_proto = out.File
	file_tlsinfo_proto_goTypes = nil
	file_tlsinfo_proto_depIdxs = nil
}
