name: Lint
on:
  pull_request:
permissions:
  contents: read
jobs:
  golangci:
    name: golangci lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --timeout=5m
  buf-breaking:
    name: incompatible proto changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: bufbuild/buf-setup-action@v1
      - uses: bufbuild/buf-breaking-action@v1
        with:
          against:  "https://github.com/Snowflake-Labs/sansshell.git#branch=main"
